"""Proof-of-vulnerability and proof-of-fix generation.

Generates complete, PR-ready artifacts:
  - Problem description (vulnerability analysis)
  - Proof-of-vulnerability test (demonstrates the bug)
  - Suggested fix (unified diff)
  - Proof-of-fix test (proves the fix works without regressions)
  - PR description markdown

This module does NOT submit PRs. It generates the artifacts that a human
or CI system can review, approve, and submit.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path

from patchsense.models import (
    FamilyProfile,
    PatchClass,
    VulnerabilityCandidate,
)
from patchsense.taxonomy import FAMILY_DESCRIPTIONS
from patchsense.backends.base import LLMBackend


@dataclass
class PRPackage:
    """A complete, PR-ready vulnerability fix package.

    Contains everything needed to submit a pull request, but does NOT
    submit it automatically — that decision belongs to a human.
    """
    # Metadata
    title: str = ""
    family: str = ""
    cwe: str = ""
    severity: str = "medium"
    file_path: str = ""

    # Problem description
    vulnerability_description: str = ""
    root_cause_analysis: str = ""

    # Proof of vulnerability
    vuln_test_code: str = ""
    vuln_test_description: str = ""

    # Fix
    fix_diff: str = ""
    fix_explanation: str = ""

    # Proof of fix
    fix_test_code: str = ""
    fix_test_description: str = ""

    # Regression check
    regression_notes: str = ""

    # Full PR body
    pr_body: str = ""

    def to_markdown(self) -> str:
        """Render the full PR package as markdown."""
        if self.pr_body:
            return self.pr_body
        return self._build_pr_body()

    def _build_pr_body(self) -> str:
        sections = []

        sections.append(f"# {self.title}\n")

        sections.append("## Vulnerability Summary\n")
        sections.append(f"**Family**: {self.family}")
        sections.append(f"**CWE**: {self.cwe}")
        sections.append(f"**Severity**: {self.severity}")
        sections.append(f"**File**: `{self.file_path}`\n")

        sections.append("## Problem Description\n")
        sections.append(self.vulnerability_description + "\n")

        sections.append("## Root Cause Analysis\n")
        sections.append(self.root_cause_analysis + "\n")

        if self.vuln_test_code:
            sections.append("## Proof of Vulnerability\n")
            sections.append(self.vuln_test_description + "\n")
            sections.append("```c")  # TODO: detect language
            sections.append(self.vuln_test_code)
            sections.append("```\n")

        sections.append("## Fix\n")
        sections.append(self.fix_explanation + "\n")
        if self.fix_diff:
            sections.append("```diff")
            sections.append(self.fix_diff)
            sections.append("```\n")

        if self.fix_test_code:
            sections.append("## Proof of Fix\n")
            sections.append(self.fix_test_description + "\n")
            sections.append("```c")
            sections.append(self.fix_test_code)
            sections.append("```\n")

        if self.regression_notes:
            sections.append("## Regression Notes\n")
            sections.append(self.regression_notes + "\n")

        sections.append("---")
        sections.append("*Generated by PatchSense vulnerability detection pipeline.*")
        sections.append("*Review carefully before merging — this is a suggestion, not an assertion.*")

        return "\n".join(sections)

    def write_to_directory(self, output_dir: Path) -> dict[str, Path]:
        """Write all artifacts to a directory structure.

        Returns a dict of artifact_name → file path.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        files = {}

        # PR description
        pr_path = output_dir / "PR_DESCRIPTION.md"
        pr_path.write_text(self.to_markdown())
        files["pr_description"] = pr_path

        # Fix diff
        if self.fix_diff:
            diff_path = output_dir / "fix.patch"
            diff_path.write_text(self.fix_diff)
            files["fix_diff"] = diff_path

        # Vulnerability test
        if self.vuln_test_code:
            ext = "c" if "int main" in self.vuln_test_code else "java"
            vuln_test_path = output_dir / f"test_vulnerability.{ext}"
            vuln_test_path.write_text(self.vuln_test_code)
            files["vuln_test"] = vuln_test_path

        # Fix test
        if self.fix_test_code:
            ext = "c" if "int main" in self.fix_test_code else "java"
            fix_test_path = output_dir / f"test_fix.{ext}"
            fix_test_path.write_text(self.fix_test_code)
            files["fix_test"] = fix_test_path

        return files


_PR_SYSTEM_PROMPT = (
    "You are a senior security engineer writing a pull request to fix a "
    "vulnerability. Your PR must be thorough, well-documented, and include "
    "both a proof of vulnerability and proof of fix. The PR should convince "
    "a reviewer that: (1) the vulnerability is real, (2) the fix addresses "
    "the root cause, (3) no regressions are introduced."
)

_PR_USER_TEMPLATE = """\
Generate a complete pull request package for this vulnerability fix.

=== VULNERABILITY ===
Family: {family}
CWE: {cwe}
File: {file_path}
Description: {description}

=== VULNERABLE CODE ===
```
{code_snippet}
```

=== FAMILY CONTEXT ===
{family_description}

=== TASK ===
Generate a JSON object with ALL of these fields:
{{
  "title": "Short PR title (under 70 chars)",
  "severity": "low|medium|high|critical",
  "vulnerability_description": "Detailed description of the vulnerability and its impact",
  "root_cause_analysis": "What is fundamentally wrong and why (not just what fails)",
  "vuln_test_code": "Complete, compilable test that demonstrates the vulnerability (triggers crash/OOB/etc on unpatched code)",
  "vuln_test_description": "What this test does and what to expect",
  "fix_diff": "Unified diff that fixes the root cause",
  "fix_explanation": "Why this fix addresses the root cause rather than suppressing symptoms",
  "fix_test_code": "Complete test that passes on fixed code and would fail on vulnerable code",
  "fix_test_description": "What this test verifies",
  "regression_notes": "What behaviors should be verified to ensure no regressions"
}}"""


def generate_pr_package(
    candidate: VulnerabilityCandidate,
    source: str,
    backend: LLMBackend,
) -> PRPackage:
    """Generate a complete PR-ready fix package for a vulnerability.

    Args:
        candidate: Confirmed vulnerability candidate.
        source: Full source code of the file.
        backend: LLM backend for generation.

    Returns:
        PRPackage with all artifacts (does NOT submit a PR).
    """
    lines = source.split("\n")
    start = max(0, candidate.line_range[0] - 15)
    end = min(len(lines), candidate.line_range[1] + 25)
    code_snippet = "\n".join(
        f"{i + start + 1:4d}: {lines[i + start]}"
        for i in range(min(end - start, 60))
    )

    family_desc = FAMILY_DESCRIPTIONS.get(candidate.family, "")

    user_prompt = _PR_USER_TEMPLATE.format(
        family=candidate.family,
        cwe=candidate.cwe,
        file_path=candidate.file_path,
        description=candidate.description,
        code_snippet=code_snippet,
        family_description=family_desc,
    )

    raw = backend.complete(_PR_SYSTEM_PROMPT, user_prompt, max_tokens=4096)

    # Parse response
    package = PRPackage(
        family=candidate.family,
        cwe=candidate.cwe,
        file_path=candidate.file_path,
    )

    try:
        match = re.search(r"\{.*\}", raw, re.DOTALL)
        if match:
            resp = json.loads(match.group())
            package.title = resp.get("title", f"Fix {candidate.family} in {candidate.file_path}")
            package.severity = resp.get("severity", "medium")
            package.vulnerability_description = resp.get("vulnerability_description", "")
            package.root_cause_analysis = resp.get("root_cause_analysis", "")
            package.vuln_test_code = resp.get("vuln_test_code", "")
            package.vuln_test_description = resp.get("vuln_test_description", "")
            package.fix_diff = resp.get("fix_diff", "")
            package.fix_explanation = resp.get("fix_explanation", "")
            package.fix_test_code = resp.get("fix_test_code", "")
            package.fix_test_description = resp.get("fix_test_description", "")
            package.regression_notes = resp.get("regression_notes", "")
        else:
            # No JSON structure found — use raw response as fallback
            package.vulnerability_description = raw[:1000]
    except (json.JSONDecodeError, ValueError, TypeError):
        # Fallback: use raw response
        package.vulnerability_description = raw[:1000]

    package.pr_body = package._build_pr_body()
    return package
